### ISSUE TITLE
Some links are error

### ISSUE THREAD

**Issue by tageniu** [ustclug/website#12]
Links on page "https://lug.ustc.edu.cn/wiki/scripts/" are error.
e.g. "https://lug.ustc.edu.cn/wiki/scripts/scripts/wlt" is error, the correct link should be "https://lug.ustc.edu.cn/wiki/scripts/wlt" or "./wlt"

**Comment by taoky** [comment]
Fixed by 7c28c64a84c86c4ded4ff7086c0ef4422744b0fe.
