### ISSUE TITLE
搜索功能

### ISSUE THREAD

**Issue by taoky** [ustclug/website#14]

**Comment by iBug** [comment]
这个主题有 Algolia Search 的支持，效果应该也比静态的 Lunr 好，我自己的网站就在用

**Comment by taoky** [comment]
> 这个主题有 Algolia Search 的支持，效果应该也比静态的 Lunr 好，我自己的网站就在用

Algolia Search 似乎有每个月 10000 次搜索的限制。静态 Lunr + 一个提示可以使用搜索引擎搜索的链接 (keyword + site:lug.ustc.edu.cn) 可能会好一点？要是有这种简单的搜索后端可以自己搭就好了。

**Comment by zhsj** [comment]
可以看看有没有中文分词的插件，效果应该还行，比如试试 http://mirrors.ustc.edu.cn/help/ 的搜索。

**Comment by iBug** [comment]
> Algolia Search 似乎有每个月 10000 次搜索的限制

我自己的账号下还有一个旧款的无限制的 Community Plan，可以一试

**Comment by iBug** [comment]
> 我自己的账号下还有一个旧款的无限制的 Community Plan，可以一试

先拿这个上了
