### ISSUE TITLE
news、planet 添加 RSS 订阅

### ISSUE THREAD

**Issue by yuanyiwei** [ustclug/website#15]

**Comment by iBug** [comment]
https://github.com/ustclug/website/pull/16#issuecomment-744025173

**Comment by zhsj** [comment]
似乎是坏的？

https://lug.ustc.edu.cn/feed.xml 是空的，subtitle还是`Under construction`

**Comment by iBug** [comment]
我把这茬给忘了，明天写点代码处理一下吧
