### ISSUE TITLE
关于opensuse-guide

### ISSUE THREAD

**Issue by xinyuzhong** [ustclug/website#18]
记得以前有个opensuse guide的中文网站，现在怎么没有了吗，还是地址变了，有哪位小伙伴告知一下？

**Comment by iBug** [comment]
请问你要找的是 <https://opensuse-guide.ustclug.org/> 吗？

**Comment by taoky** [comment]
> 请问你要找的是 https://opensuse-guide.ustclug.org/ 吗？

我搜了一下 Google，发现有一些 URL 是 http://lug.ustc.edu.cn/sites/opensuse-guide/ 格式的，可能需要设置 302 跳转到 <https://opensuse-guide.ustclug.org/>。

**Comment by taoky** [comment]
跳转问题已经修复。

**Comment by xinyuzhong** [comment]
> 请问你要找的是 https://opensuse-guide.ustclug.org/ 吗？



> 请问你要找的是 https://opensuse-guide.ustclug.org/ 吗？

谢谢.
