### ISSUE TITLE
https://lug.ustc.edu.cn/wiki/lug/services/revproxy 404

### ISSUE THREAD

**Issue by jiacai2050** [ustclug/website#28]
- https://lug.ustc.edu.cn/wiki/lug/services/revproxy
之前会代理 Google 字体之类的资源，现在是不提供了吗？ 

PS：我的插件用到了这个资源：https://github.com/jiacai2050/gooreplacer/issues/115

**Comment by taoky** [comment]
See https://github.com/ustclug/discussions/issues/325
