### ISSUE TITLE
https://lug.ustc.edu.cn/wiki/user/vastuniverse/lug-upgrade-failure 链接404

### ISSUE THREAD

**Issue by TurnOffNOD** [ustclug/website#31]
如题

**Comment by taoky** [comment]
Fixed in 4a76e96b453cc942e4b4ad54127ea52b0148b5b8.

目前手动转换成了 markdown 排版，并且根据之前 wiki 的文件修改时间，开头标注了时间为 2013 年，如果有问题的话可告知。
