### ISSUE TITLE
Dead link: 提问的智慧 页面存在无效链接

### ISSUE THREAD

**Issue by recolic** [ustclug/website#32]
你好. 我通过此链接 <https://lug.ustc.edu.cn/wiki/doc/smart-questions/> 访问提问的智慧页面, 然后点击第一屏的`本文另有[繁體中文版]。`链接, 就会跳转到404错误页面. 

存在dead link的html连结很可能位于此文件: <https://github.com/ustclug/website/blob/4a76e96b453cc942e4b4ad54127ea52b0148b5b8/pages/_wiki/doc/smart-questions.md?plain=1#L20>

Thanks

**Comment by taoky** [comment]
Fixed in 8e952341a6ae16a9ce8cde12bd5697c2a51774ce
