### ISSUE TITLE
typos and mistakes in the article keeping-account-with-beancount

### ISSUE THREAD

**Issue by liginity** [ustclug/website#7]
[keeping-account-with-beancount](https://github.com/ustclug/website/blob/master/pages/_planet/2020-08-06-keeping-account-with-beancount.md) has typos in the sub section [将当日的一卡通消费生成为 CSV](https://github.com/ustclug/website/blob/master/pages/_planet/2020-08-06-keeping-account-with-beancount.md#%E5%B0%86%E5%BD%93%E6%97%A5%E7%9A%84%E4%B8%80%E5%8D%A1%E9%80%9A%E6%B6%88%E8%B4%B9%E7%94%9F%E6%88%90%E4%B8%BA-csv), such as
- error in the code sample (the source in the repository works, but the code sample in the article has errors)
- typo for the file name **crawer**

sorry that I am not familiar with working on GitHub.  I don't know how to write the issue in a better way. Em, the link to the file is not version specific.

By the way, is it better to make a pull request to fix this kind of problem?

**Comment by taoky** [comment]
@CharlesLiu7

**Comment by CharlesLiu7** [comment]
Thanks for pointing out the problem. @liginity 

I have modified the article and created a [pr](https://github.com/ustclug/website/pull/8) based on your question and we can discuss it at the pr.

**Comment by taoky** [comment]
#8 has been merged.
