### ISSUE TITLE
我确信这里有个页面，但是404not found

### ISSUE THREAD

**Issue by wheneveright** [ustclug/website#91]
https://lug.ustc.edu.cn/wiki/lug/contribute/services.md

**Comment by taoky** [comment]
应该是 <https://lug.ustc.edu.cn/wiki/lug/services/>？

**Comment by wheneveright** [comment]
> 应该是 https://lug.ustc.edu.cn/wiki/lug/services/？

看起来是的，” 想为 LUG [项目](https://lug.ustc.edu.cn/wiki/lug/contribute/services.md)做出贡献？你可以：“连的是.md
